FROM python:3.8-slim-buster

ARG ENV="dev"
ENV ENV=${ENV} \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.1.4 \
  HOST=0.0.0.0 \
  PORT=6006

RUN apt-get update && apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
    ghostscript tesseract-ocr tesseract-ocr-eng tesseract-ocr-fra tesseract-ocr-nld

RUN pip install "poetry==$POETRY_VERSION" 
RUN apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app
COPY poetry.lock pyproject.toml /app/
COPY . /app
RUN poetry config virtualenvs.create false && \
    poetry install $(test $ENV == "prod" && echo "--no-dev") --no-interaction --no-ansi


EXPOSE 5000
ENTRYPOINT ["poetry", "run", "api"]
LABEL maintainer="Pieterjan Montens, 2020"
